spring.application.name=AISpringBoot

spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.base-url=https://aicafe.hcl.com/AICafeService/api/v1/subscription

spring.ai.openai.chat.completions-path=/openai/deployments/gpt-4.1/chat/completions?api-version=2024-12-01-pre
spring.ai.openai.chat.options.model=gpt-4.1
spring.ai.openai.chat.options.http-headers.api-key=${OPEN_API_KEY}
server.port=1111